 # This file controls the settings for your Quarto template from www.marvinschmitt.com

# website settings
website:
  title: "Katie Braun"                                # Your name
  description: "Studying the Earth from land and space"   # A brief slogan (optional)
  image: img/Katie_Braun
  
  favicon: img/favicon.png
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    logo: /img/logo.png
    search: true
    # your sub-pages
    left:
      # - text: "Research"
      #   href: research/research.qmd
      - text: "Publications"
        href: pubs/pubs.qmd
      - text: "Research"
        file: research/research.qmd
      - text: "From the Field"
        href: updates/updates.qmd
      # - text: "Teaching and Outreach"
      #   href: outreach/outreach.qmd
    # your social media handles
    right:
      # - icon: github
      #   href: https://github.com/katie-braun
      - icon: book
        href: https://scholar.google.com/citations?user=4-7sjHIAAAAJ&hl=en&oi=ao
      - icon: envelope
        aria-label: email
        href: "mailto:knbraun@wisc.edu"  
  
  # sidebar:
 # - title: "Research"
  #  style: "docked"
   # background: light
    #contents:
     # - research/research.qmd
      #- research/permafrost.qmd
      #- research/carbon.qmd
      #- research/coast.qmd
      #- research/wood.qmd

# Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: textbox
  page-footer: 
    right: |
      <span class="faux-block"><a href="https://github.com/marvinschmitt/quarto-website-template/">View website source on GitHub</a></span>

project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - pulse
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true